// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfBHBq.Migrations
{
    [DbContext(typeof(BHBqContext))]
    [Migration("20240116080756_Initial lots")]
    partial class Initiallots
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("APE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Activite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Siege")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Siret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entreprises");
                });

            modelBuilder.Entity("Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CoefPose")
                        .HasColumnType("REAL");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdSousLot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("TauxTVA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeTVA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Taux")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TauxTVAs");
                });
#pragma warning restore 612, 618
        }
    }
}
