@startuml BHBq_Diagram

skinparam defaultFontName Arial
skinparam linetype ortho
skinparam linewidth 2
skinparam roundcorner 15

' Classe représentant un article qui apparaitra comme une ligne sur le devis
class Article #lightblue {
  + Id: int [PK]
  + IdLot: int [FK]
  + Nom: string
  + Unite: string
  + PrixH: double
  + PrixM: double
  + PrixB: double
  + Calcul: string

  + Article()
}

' Classe représentant un client du Groupe BHB
class Client #lightyellow {
  + Id: int [PK]
  + Nom: string
  + Adresse: string
  + Particulier: bool
  + Siret: string?
  + TvaIntracom: string?

  + Client()
}

' Classe représentant une entreprise du groupe BHB
class Entreprise #lightgreen {
  + Id: int [PK]
  + Nom: string
  + Adresse: string
  + Siret: string
  + TvaIntracom: string
  + Logo: string?

  + Entreprise()
}

' Classe représentant un lot (ensemble d'articles)
class Lot #orange {
  + Id: int [PK]
  + IdEntreprise: int? [FK]
  + Designation: string
  + CoefPose: double?

  + Lot()
}

' Classe représentant un projet, qui regroupe les informations relatives à un projet
class Projet #lightpink {
  + Id: int [PK]
  + IdClient: int [FK]
  + Description: string
  + DateDebut: DateTime
  + DateFin: DateTime

  + Projet()
}

' Classe représentant l'ensemble des paramètres modélisation une ou plusieurs constructions
class Param #lightgrey {
  + Id: int [PK]
  + IdProjet: int [FK]
  + Param1: int
  + Param2: int

  + Param()
}

' Classe représentant un document type Facture, Devis, Avenant, etc.
class Document #lightcyan {
  + Id: int [PK]
  + IdProjet: int [FK]
  + IdEntreprise: int [FK]

  + Document()
}

' Relations entre les classes
Projet "1" -- "1" Client
Projet "1" *- "*" Document
Projet "1" *- "1" Param
Document *- Lot
Lot *- Article
Document "1" -- "1" Entreprise

@enduml